# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-init',
                'doc_host': 'https://avats-dev.github.io',
                'git_url': 'https://github.com/avats-dev/nbdev-init',
                'lib_path': 'nbdev_init'},
  'syms': {'nbdev_init.core': {'nbdev_init.core.foo': ('core.html#foo', 'nbdev_init/core.py')}}}
